### PR TITLE
Use npm instead of Yarn

### PR DESCRIPTION
**Pull request by nickmccurdy**

### CODE REVIEW

**Comment by benmonro** [comment]
Curious... Was this causing an issue for you?

**Comment by nickmccurdy** [comment]
No, I'm just moving all repositories to npm for consistency. You can keep Yarn if you need it, but there's not much of an advantage without a lock file.

**Comment by benmonro** [comment]
Nope that's fine was just curious

**Comment by benmonro** [comment]
@all-contributors please add @nickmccurdy for code

**Pull request merged**
